esphome:
  name: air-gradient-david
  friendly_name: Air-Gradient David

esp8266:
  board: d1_mini_pro

logger:
  level: INFO

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

i2c:
  sda: D2
  scl: D1
  frequency: 400kHz

font:
  - file: "font/pixelmix.ttf"
    id: opensans
    size: 8

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 64x48"
    pages:
      - id: page1
        lambda: |-
          it.printf(0, 0, id(opensans), "CO2: %.0fppm", id(co2).state);
          it.printf(0, 12, id(opensans), "PM25: %.0f", id(pm25).state);
          it.printf(0, 24, id(opensans), "Hmdty: %.1f%%", id(humidity).state);
          it.printf(0, 36, id(opensans), "Temp: %.1fC", id(temp).state);

interval:
  - interval: 5s
    then:
      - display.page.show_next: oled
      - component.update: oled

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_1

  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "Temperature"
    humidity:
      id: humidity
      name: "Humidity"
    address: 0x44
    update_interval: 5s

  - platform: pmsx003
    type: PMS5003T
    uart_id: uart_1
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
    update_interval: 30s

  - platform: senseair
    uart_id: uart_2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 60s
